on:
  pull_request:
    types:
      - closed
    branches:
      - main

name: Release Management

permissions: read-all

jobs:
  release_management:
    name: Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.1
      - name: Build
        uses: domix24/action-gitflow@v0
        with:
          dev_branch: develop
          main_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
