name: Update Version
run-name: Move ${{ github.event.inputs.version }} to ${{ github.event.inputs.target }}

# checkov:skip=CKV_GHA_7:Inputs are required for manual triggering of this workflow
on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        description: The tag or reference to use (from)
      version:
        required: true
        description: The version to use (to)

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    name: Update Tag
    steps:
      - uses: actions/checkout@v5.0.1
        with:
          fetch-depth: 0
      - name: Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Git Tag
        run: git tag -f ${{ github.event.inputs.version }} ${{ github.event.inputs.target }}
      - name: Git Push
        run: git push -f origin ${{ github.event.inputs.version }}
